"""empty message

Revision ID: 84d89249f83e
Revises: 1d39c83fee89
Create Date: 2024-11-25 16:50:28.453298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84d89249f83e'
down_revision = '1d39c83fee89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=False, server_default="Default Name"))
        batch_op.add_column(sa.Column('last_name', sa.String(length=80), nullable=False, server_default="Default Last Name"))
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=False, server_default="0"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('weight')
        batch_op.drop_column('height')
        batch_op.drop_column('last_name')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
