"""empty message

Revision ID: e54bd55e7277
Revises: 84d89249f83e
Create Date: 2024-11-25 18:29:52.277434

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e54bd55e7277'
down_revision = '84d89249f83e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True,
               existing_server_default=sa.text("'Default Name'::character varying"))
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True,
               existing_server_default=sa.text("'Default Last Name'::character varying"))
        batch_op.alter_column('height',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
        batch_op.alter_column('weight',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
        batch_op.alter_column('height',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False,
               existing_server_default=sa.text("'Default Last Name'::character varying"))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False,
               existing_server_default=sa.text("'Default Name'::character varying"))

    # ### end Alembic commands ###
